version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: nginx:latest
    restart: always
    container_name: frontend_server
    ports:
      - '80:80'
    volumes:
      - ./public:/usr/share/nginx/html

  backend:
    image: node:latest
    restart: always
    container_name: backend_server
    ports:
      - '3002:3002'
    volumes:
      - ./services.js:/app/services.js
      - ./package.json:/app/package.json
    working_dir: /app
    command: sh -c "npm install && npm run start"
    depends_on:
      - postgres